version = 0.1
[default.deploy.parameters]
stack_name = "fastapi-dynamodb"
resolve_s3 = true
s3_prefix = "fastapi-dynamodb"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
